package com.takago.app.network;
import android.content.Context;import com.takago.app.db.DatabaseHelper;import com.takago.app.db.SessionManager;import org.json.JSONArray;import org.json.JSONObject;
public final class ServerSyncManager{private static long lastSync;private static volatile boolean trackingSyncInFlight;private static final String[] RESOURCES={"users","wards","vehicles","pickups","notifications","pricing_settings"};private ServerSyncManager(){}
 public static synchronized void syncAll(Context context){if(System.currentTimeMillis()-lastSync<1000)return;SessionManager session=new SessionManager(context);if(!session.isLoggedIn()||session.getApiToken().isEmpty())return;lastSync=System.currentTimeMillis();sync(context.getApplicationContext(),session.getApiToken(),0);}
 private static void sync(Context context,String token,int index){if(index>=RESOURCES.length)return;String resource=RESOURCES[index];ApiClient.get("/"+resource,token,new ApiClient.JsonCallback(){public void onSuccess(JSONObject json){JSONArray rows=json.optJSONArray("data");if(rows!=null)new DatabaseHelper(context).syncServerResource(resource,rows);sync(context,token,index+1);}public void onError(String message){ if(message != null && message.toLowerCase().contains("maintenance")) new android.os.Handler(android.os.Looper.getMainLooper()).post(() -> android.widget.Toast.makeText(context, message, android.widget.Toast.LENGTH_LONG).show()); sync(context,token,index+1);}});}
 public static void syncTracking(Context context,Runnable complete){SessionManager session=new SessionManager(context);if(!session.isLoggedIn()||session.getApiToken().isEmpty()){if(complete!=null)new android.os.Handler(android.os.Looper.getMainLooper()).post(complete);return;}if(trackingSyncInFlight){new android.os.Handler(android.os.Looper.getMainLooper()).postDelayed(()->syncTracking(context,complete),200);return;}trackingSyncInFlight=true;Context app=context.getApplicationContext();syncTrackingResource(app,session.getApiToken(),"users",()->syncTrackingResource(app,session.getApiToken(),"pickups",()->{trackingSyncInFlight=false;if(complete!=null)new android.os.Handler(android.os.Looper.getMainLooper()).post(complete);}));}
 private static void syncTrackingResource(Context context,String token,String resource,Runnable complete){ApiClient.get("/"+resource,token,new ApiClient.JsonCallback(){private void done(){if(complete!=null)complete.run();}public void onSuccess(JSONObject json){JSONArray rows=json.optJSONArray("data");if(rows!=null)new DatabaseHelper(context).syncServerResource(resource,rows);done();}public void onError(String message){done();}});}
 public static void pushPickupStatus(Context context,int pickupId,String status,String response,String reason){transition(context,pickupId,status,null,null,reason,error->{});}
 public static void acceptAndStart(Context context,int pickupId,ResultCallback callback){transition(context,pickupId,"accepted",null,null,null,error->{if(error!=null){callback.done(error);return;}transition(context,pickupId,"on_the_way",null,null,null,callback);});}
 public static void transition(Context context,int pickupId,String status,Double latitude,Double longitude,String notes,ResultCallback callback){SessionManager s=new SessionManager(context);if(s.getApiToken().isEmpty()){callback.done("Not signed in");return;}try{JSONObject body=new JSONObject().put("status",status);if(latitude!=null)body.put("latitude",latitude);if(longitude!=null)body.put("longitude",longitude);if(notes!=null)body.put("notes",notes);ApiClient.patch("/pickups/"+pickupId+"/transition",s.getApiToken(),body,new ApiClient.JsonCallback(){public void onSuccess(JSONObject json){applyPickupResponse(context,json);lastSync=0;callback.done(null);syncTracking(context,()->syncAll(context));}public void onError(String message){callback.done(message);}});}catch(Exception e){callback.done(e.getMessage());}}
 public static void pushDriverLocation(Context context,int userId,double latitude,double longitude){SessionManager s=new SessionManager(context);if(s.getApiToken().isEmpty()||s.getUserId()!=userId)return;try{ApiClient.patch("/users/"+userId,s.getApiToken(),new JSONObject().put("latitude",latitude).put("longitude",longitude),new ApiClient.JsonCallback(){public void onSuccess(JSONObject json){}public void onError(String message){}});}catch(Exception ignored){}}
 public static void finalizePickup(Context context,int pickupId,double measuredWeightKg,ResultCallback callback){SessionManager s=new SessionManager(context);try{ApiClient.post("/pickups/"+pickupId+"/finalize",s.getApiToken(),new JSONObject().put("measured_weight_kg",measuredWeightKg),new ApiClient.JsonCallback(){public void onSuccess(JSONObject json){applyPickupResponse(context,json);lastSync=0;callback.done(null);syncTracking(context,()->syncAll(context));}public void onError(String message){callback.done(message);}});}catch(Exception e){callback.done(e.getMessage());}}
 public static void assignPickup(Context context,int pickupId,int driverId,ResultCallback callback){SessionManager s=new SessionManager(context);try{ApiClient.patch("/pickups/"+pickupId+"/assign",s.getApiToken(),new JSONObject().put("driver_id",driverId),new ApiClient.JsonCallback(){public void onSuccess(JSONObject json){applyPickupResponse(context,json);lastSync=0;callback.done(null);syncTracking(context,()->syncAll(context));}public void onError(String message){callback.done(message);}});}catch(Exception e){callback.done(e.getMessage());}}
 public static boolean applyPickupResponse(Context context,JSONObject response){JSONObject pickup=response==null?null:response.optJSONObject("data");if(pickup==null||pickup.optInt("id",0)<=0)return false;JSONArray rows=new JSONArray();rows.put(pickup);new DatabaseHelper(context.getApplicationContext()).syncServerResource("pickups",rows);return true;}
 public interface ResultCallback{void done(String error);}}
