package com.takago.app.resident;
import android.os.Bundle;import android.graphics.Color;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import com.takago.app.db.SessionManager;import com.takago.app.network.ApiClient;import org.json.*;
public class ResidentComplaintsActivity extends AppCompatActivity{
 private LinearLayout list;private EditText subject,message;private SessionManager session;
 @Override public void onCreate(Bundle b){super.onCreate(b);session=new SessionManager(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(32,48,32,32);TextView title=text("Complaints",24);root.addView(title);subject=input("Subject");message=input("Describe the problem (at least 10 characters)");message.setMinLines(4);root.addView(subject);root.addView(message);Button submit=new Button(this);submit.setText("Submit complaint");root.addView(submit);TextView history=text("My complaints",20);root.addView(history);ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);submit.setOnClickListener(v->submit());load();}
 private void submit(){try{String s=subject.getText().toString().trim(),m=message.getText().toString().trim();if(s.length()<3||m.length()<10){toast("Enter a subject and a detailed message");return;}ApiClient.post("/complaints",session.getApiToken(),new JSONObject().put("subject",s).put("message",m),new ApiClient.JsonCallback(){public void onSuccess(JSONObject j){runOnUiThread(()->{subject.setText("");message.setText("");toast("Complaint submitted");load();});}public void onError(String e){runOnUiThread(()->toast(e));}});}catch(Exception e){toast(e.getMessage());}}
 private void load(){ApiClient.get("/complaints",session.getApiToken(),new ApiClient.JsonCallback(){public void onSuccess(JSONObject j){runOnUiThread(()->{list.removeAllViews();JSONArray a=j.optJSONArray("data");if(a==null||a.length()==0){list.addView(text("No complaints submitted yet.",15));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);TextView row=text(x.optString("subject")+"\n"+x.optString("message")+"\nStatus: "+x.optString("status")+(x.optString("resolution").isEmpty()?"":"\nResponse: "+x.optString("resolution")),16);row.setBackgroundColor(Color.WHITE);row.setPadding(24,20,24,20);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,8,0,8);list.addView(row,p);}});}public void onError(String e){runOnUiThread(()->toast(e));}});}
 private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setPadding(16,12,16,12);return e;}private TextView text(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(20,45,40));v.setPadding(0,12,0,12);return v;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
